spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jackson:
    property-naming-strategy: SNAKE_CASE
logging:
  level:
    org.springframework.security: DEBUG
