CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "phone" varchar,
  "enabled" bool,
  "created_at" timestamp
);

CREATE TABLE "users_profiles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "role" varchar,
  "nickname" varchar,
  "bio" text,
  "enabled" bool
);

CREATE TABLE "spaces" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "host_profile_id" integer NOT NULL,
  "category_id" integer NOT NULL,
  "description" varchar,
  "phone1" varchar,
  "phone2" varchar,
  "email" varchar,
  "close_start" time,
  "close_end" time,
  "is_closed_at_public_holidays" bool,
  "is_visible" bool,
  "deleted_at" timestamp
);

CREATE TABLE "subspaces" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "space_id" integer NOT NULL,
  "description" varchar,
  "min_hours" integer,
  "max_hours" integer,
  "is_visible" bool,
  "deleted_at" timestamp
);

CREATE TABLE "categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL
);

CREATE TABLE "reservations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "subspace_id" integer NOT NULL,
  "renter_profile_id" integer NOT NULL,
  "start" timestamp NOT NULL,
  "end" timestamp NOT NULL,
  "status" varchar NOT NULL,
  "renter_name" varchar,
  "renter_phone" varchar,
  "renter_email" varchar,
  "custom_request" varchar,
  "created_at" timestamp NOT NULL,
  "status_updated_at" timestamp,
  "cancelled_at" timestamp,
  "cancelled_by" integer
);

CREATE TABLE "holiday_rule" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "space_id" integer NOT NULL,
  "frequency_type" varchar,
  "day_mask" smallint,
  "nth_occurrence" smallint
);

CREATE TABLE "holiday_override" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "space_id" integer NOT NULL,
  "starts_at" date,
  "ends_at" date,
  "is_closed" bool,
  "day_mask" smallint,
  "priority_weight" integer
);

CREATE TABLE "images" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_url" varchar NOT NULL
);

CREATE TABLE "spaces_images" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "space_id" integer,
  "image_id" integer,
  "order_seq" integer
);

CREATE TABLE "subspaces_images" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "subspace_id" integer,
  "image_id" integer,
  "order_seq" integer
);

CREATE INDEX ON "users" ("email");

CREATE INDEX ON "users" ("phone");

CREATE INDEX ON "users_profiles" ("user_id");

CREATE INDEX ON "spaces" ("host_profile_id");

CREATE INDEX ON "spaces" ("category_id");

CREATE INDEX ON "spaces" ("phone1");

CREATE INDEX ON "spaces" ("email");

CREATE INDEX ON "subspaces" ("space_id");

CREATE INDEX ON "reservations" ("subspace_id");

CREATE INDEX ON "reservations" ("renter_profile_id");

CREATE INDEX ON "reservations" ("renter_phone");

CREATE INDEX ON "reservations" ("renter_email");

CREATE INDEX ON "reservations" ("created_at");

CREATE INDEX ON "reservations" ("cancelled_by");

CREATE INDEX ON "reservations" ("subspace_id", "start", "end");

CREATE INDEX ON "holiday_rule" ("space_id");

CREATE INDEX ON "holiday_override" ("space_id");

CREATE INDEX ON "images" ("full_url");

CREATE INDEX ON "spaces_images" ("image_id");

CREATE INDEX ON "spaces_images" ("space_id");

CREATE INDEX ON "subspaces_images" ("image_id");

CREATE INDEX ON "subspaces_images" ("subspace_id");

COMMENT ON COLUMN "spaces"."phone1" IS 'allows different contacts for different spaces.';

COMMENT ON COLUMN "spaces"."phone2" IS 'allows different contacts for different spaces.';

COMMENT ON COLUMN "spaces"."email" IS 'allows different contacts for different spaces.';

COMMENT ON COLUMN "spaces"."close_start" IS 'The time space closes';

COMMENT ON COLUMN "spaces"."close_end" IS 'The time space opens. If `close_start` and `close_end` equals, the space stays open 24 hours a day.';

COMMENT ON COLUMN "reservations"."renter_name" IS 'Don''t use `users` table because 1. prevent sharing the latest renter info. to hosts 2. allow renters to reserve a space under a different person';

COMMENT ON TABLE "holiday_rule" IS '## Scenario A: "Every even week on Thursdays"
Entity: holiday_rule
Mapping: frequency_type = BI_WEEKLY, day_mask = 16, nth_occurrence = 0.
Verification: The system safely evaluates this by checking if the target date is a Thursday, then checking if ISO_WEEK % 2 == 0.

## Scenario B: "Every month on the 15th"
Entity: holiday_rule
Mapping: frequency_type = MONTHLY_FIXED_DATE, day_mask = 0 (ignored), nth_occurrence = 15.
Verification: The system completely bypasses the bitwise day math and strictly checks if targetDate.getDayOfMonth() == 15.

## Scenario C: "Every last week of the month on Fridays"
Entity: holidayRule
Mapping: frequency_type = MONTHLY_CALENDAR_WEEK, day_mask = 32, nth_occurrence = -1.
Verification: Safely accommodates 4-week, 5-week, and 6-week months by finding the visual calendar week of the actual last day of the target month, and matching it against the current date''s calendar week.
  ';

COMMENT ON COLUMN "holiday_rule"."frequency_type" IS 'Defines the temporal math. One of `WEEKLY`, `BI_WEEKLY`, `MONTHLY_NTH_OCCURRENCE`, `MONTHLY_CALENDAR_WEEK`,`MONTHLY_FIXED_DATE`, `LAST_DAY_OF_MONTH`.';

COMMENT ON COLUMN "holiday_rule"."day_mask" IS 'The sum of the target days of the week (Sun=1, Mon=2, Tue=4... Sat=64). Defaults to 127 (all days) if not applicable(`MONTHLY_FIXED_DATE`, `LAST_DAY_OF_MONTH`).';

COMMENT ON COLUMN "holiday_rule"."nth_occurrence" IS 'The modifier for the frequency type. Ignored for `WEEKLY` and `LAST_DAY_OF_MONTH`. For `BI_WEEKLY` frequency type, `0`` means every even week of the month and `1` means every odd week of the month.';

COMMENT ON TABLE "holiday_override" IS '## Scenario : "Closed March 20–27, but only on Mon/Tue"
Entity: HolidayOverride
Mapping: start_date = 2026-03-20, end_date = 2026-03-27, is_closed = TRUE, day_mask = 6 (2 + 4).
Verification: When generating availability for March 2026, the engine evaluates this Priority 1 override. It sees a date falls within the range, but only triggers the is_closed status if the date''s bitwise day matches 6.
';

COMMENT ON COLUMN "holiday_override"."is_closed" IS 'TRUE to force a closure, FALSE to force an opening (e.g., opening on a normally closed holiday).';

COMMENT ON COLUMN "holiday_override"."day_mask" IS 'The sum of the target days of the week (Sun=1, Mon=2, Tue=4, ... Sat=64). Determines which days within the date range are affected. Defaults to 127.';

COMMENT ON COLUMN "holiday_override"."priority_weight" IS 'Used to resolve conflicts if multiple overrides overlap the exact same dates and duration. Higher numbers win.';

ALTER TABLE "users_profiles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE users_profiles ADD CONSTRAINT uk_user_role UNIQUE (user_id, role);

ALTER TABLE "reservations" ADD FOREIGN KEY ("renter_profile_id") REFERENCES "users_profiles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reservations" ADD FOREIGN KEY ("cancelled_by") REFERENCES "users_profiles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "holiday_rule" ADD FOREIGN KEY ("space_id") REFERENCES "spaces" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "holiday_override" ADD FOREIGN KEY ("space_id") REFERENCES "spaces" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "spaces_images" ADD FOREIGN KEY ("space_id") REFERENCES "spaces" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "spaces_images" ADD FOREIGN KEY ("image_id") REFERENCES "images" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "subspaces_images" ADD FOREIGN KEY ("subspace_id") REFERENCES "subspaces" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "subspaces_images" ADD FOREIGN KEY ("image_id") REFERENCES "images" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "spaces" ADD CONSTRAINT "host_spaces" FOREIGN KEY ("host_profile_id") REFERENCES "users_profiles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "spaces" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "subspaces" ADD FOREIGN KEY ("space_id") REFERENCES "spaces" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reservations" ADD FOREIGN KEY ("subspace_id") REFERENCES "subspaces" ("id") DEFERRABLE INITIALLY IMMEDIATE;
